version: '3'
services:
    nifi:
        image: mkobit/nifi
        ports:
            - 8080:8080
            - 8081:8081
        volumes:
            - ./data:/mnt/data
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=nifi
            - POSTGRES_PASSWORD=nifi
            - POSTGRES_DB=nifi
        ports:
            - 5432:5432